[package]
name = "prover-research"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blake2 = "0.10.6"
blake3 = "1.5.0"
hex = "0.4.3"
num-traits = "0.2.17"
rayon = "1.8.0"

[dev-dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }
rand = "0.8.3"

[profile.bench]
codegen-units = 1
lto = true

[[bench]]
name = "merkle_bench"
harness = false
