cargo-features = ["profile-rustflags"]

[package]
name = "prover_research"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"
once_cell = "1.8"

[dev-dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }

[profile.release]
opt-level = 2
rustflags = ["-C", "target-cpu=native", "-C", "target-feature=+avx512f"]
debug = 2


[[bench]]
name = "field"
harness = false

