cargo-features = ["profile-rustflags"]

[package]
name = "prover_research"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blake3 = "1.4.1"
rayon = "1.7.0"

[dev-dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }

[profile.release]
opt-level = 2
rustflags = ["-C", "target-cpu=skylake-avx512", "-C", "target-feature=+avx512f"]
debug = 2

[[bench]]
name = "commitment"
harness = false
