# See: https://github.com/rust-lang/rustfmt/blob/master/Configurations.md
imports_granularity = "Module"
reorder_imports = true
group_imports = "StdExternalCrate"
use_field_init_shorthand = true
reorder_modules = true
wrap_comments = true
normalize_comments = true
condense_wildcard_suffixes = true
format_code_in_doc_comments = true
edition = "2021"
